In [2]:
import numpy as np
import ctypes
from utils import show_matrix, run_test_case_all_methods
dll = ctypes.CDLL('./simdrop.dll')

In [3]:
# 存储测试结果
results = []

# 定义测试用例的尺寸
test_cases = [
    ("AllZero", 5, 4, lambda w, h: [0] * (w * h)),  # 全空
    ("AllOnes", 5, 4, lambda w, h: [1] * (w * h)),  # 全障碍
    ("SingleCol", 1, 6, lambda w, h: [2, 3, 0, 4, 1, 2]),  # 单列 
    ("SingleRow", 6, 1, lambda w, h: [2, 3, 4, 1, 0, 2]),  # 单行
    ("RandomSmall", 5, 4, lambda w, h: np.random.choice(
        [0, 1, 2, 3, 4, 5], size=w*h, p=[0.3, 0.1, 0.15, 0.15, 0.15, 0.15]
    ).tolist()),  # 小随机 
    ("RandomMed", 100, 100, lambda w, h: np.random.choice(
        [0, 1, 2, 3, 4, 5], size=w*h, p=[0.3, 0.1, 0.15, 0.15, 0.15, 0.15]
    ).tolist(), 3),  # 中等随机 , 3 次
    ("RandomBig", 1000, 1000, lambda w, h: np.random.choice(
        [0, 1, 2, 3, 4, 5], size=w*h, p=[0.3, 0.1, 0.15, 0.15, 0.15, 0.15]
    ).tolist())  # 大矩阵随机 
]

# 遍历测试用例
for case in test_cases:
    name, w, h, generator = case[:4]
    iterations = case[4] if len(case) > 4 else 1  # 默认 1 次
    for i in range(iterations):
        test_name = f"{name}_{w}x{h}_iter{i+1}" if iterations > 1 else f"{name}_{w}x{h}"
        matrix = generator(w, h)
        results.append(run_test_case_all_methods(dll, test_name, matrix, w, h))

print("测试完毕！")


测试完毕！


In [4]:
# 查看并打印结果

for r in results:
    print("Test Name       :", r['test_name'])
    print("Matrix Size     :", f"{r['width']} x {r['height']}")
    
    for key in r['sim_funcs']:
        print(f"Time({key})     : {r['timings'][key]} s")
    for pair, eq in r['equal_results'].items():
        print(f"Equal Result ({pair}):", eq)
    
    print("\n-- Initial matrix --")
    show_matrix(r['initial_matrix'], r['width'], r['height'])
    
    for key in r['sim_funcs']:
        print(f"\n-- {key.capitalize()} final matrix --")
        show_matrix(r['results'][key], r['width'], r['height'])
    
    print("-------------------------------------------\n")


Test Name       : AllZero_5x4
Matrix Size     : 5 x 4
Time(multi)     : 0.0 s
Time(single)     : 0.0 s
Time(queue)     : 0.0 s
Time(active)     : 0.0 s
Equal Result (multi vs single): True
Equal Result (multi vs queue): True
Equal Result (multi vs active): True
Equal Result (single vs queue): True
Equal Result (single vs active): True
Equal Result (queue vs active): True

-- Initial matrix --
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

-- Multi final matrix --
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

-- Single final matrix --
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

-- Queue final matrix --
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

-- Active final matrix --
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
-------------------------------------------

Test Name       : AllOnes_5x4
Matrix Size     : 5 x 4
Time(multi)     : 0.0 s
Time(single)     : 0.0 s
Time(queue)     : 0.0 s
Time(active)     : 0.0 s
Equal Result (multi vs single): True